# Generated by Django 5.2 on 2026-10-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_app_id_alter_category_id_alter_review_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icons/'),
        ),
    ]
